files:
  - source: '*.properties'
    ignore:
      - '*.java'
      - '*.xml'
      - velocity.properties
      - '*_*.properties'
      - hibernate.properties
      - hibernate*.properties
      - log4j.properties
      - /.mvn/
      - docker/
      - chat-sql.properties
      - defaultJdbc.properties
      - schema-export-ddl.properties
      - hsqldb.properties
      - mysql.properties
      - oracle.properties
      - kernel/kernel-impl/src/test/resources/
      - config/configuration/
    translation: /%original_path%/%file_name%_%locale_with_underscore%.%file_extension%
